ASANA_ACCESS_TOKEN = 'YOUR_TOKEN'
ASANA_WORKSPACE = 'YOUR_WORKSPACE'
ASANA_TEAM = 'YOU_TEAM'
ASANA_PER_PAGE = 100

SLACK_WEBHOOK_BASE = 'https://hooks.slack.com'
SLACK_INCOMING_WEBHOOK = '/services/YOUR/WEBHOOK'
SLACK_CHANNEL = "#YOUR_CHANNEL"
SLACK_USERNAME = "YOUR_USERNAME"
SLACK_EMOJI = ":YOUR_EMOJI:"